name: nepali_month_year_picker
description: The month year picker inspired by the Flutter's date picker design.
version: 0.0.3+3
homepage: https://github.com/kojurohan42/nepali-month-year-picker.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  nepali_utils: ^3.0.3

dev_dependencies:
  flutter_lints: ^2.0.1

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:


